import Head from 'next/head'
import React, {useState, useEffect, useContext} from 'react'
import Image from 'next/image'
// INTERNAL IMPORT
import {ERC20ICOContext} from '../context/CalamansiToken'

 const Home = () => {
  const  {calamansiToken} = useContext(ERC20ICOContext)
  return (
    <>
      <Head>
        <title>Calamansi Token</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div>{calamansiToken}</div>
      
    </>
  )
}

export default Home
